import {useState} from 'react';
import {Download,Upload} from 'lucide-react';
import {applyReviewedChanges,createAiPackage,parseCampaignUpdate,reviewCampaignUpdate} from './campaignUpdate';
import type {CampaignUpdateFile,CampaignUpdateReview} from './campaignUpdate';
import {downloadJson} from './backup';
import type {AppData} from './types';
import type {CloudCampaign} from './cloud';

export function OwnerCampaignTools({campaign,loadLatest,applyChanges}:{campaign:CloudCampaign;loadLatest:()=>Promise<AppData>;applyChanges:(update:CampaignUpdateFile,selected:Set<string>)=>Promise<{applied:number;conflicts:number}>}){
  const [update,setUpdate]=useState<CampaignUpdateFile|null>(null),[reviews,setReviews]=useState<CampaignUpdateReview[]>([]),[selected,setSelected]=useState(new Set<string>()),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  if(campaign.role!=='owner')return null;
  const exportPackage=async()=>{setBusy(true);setMessage('Collecting the latest shared campaign information…');try{const latest=await loadLatest();downloadJson(`${campaign.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-ai-package.json`,createAiPackage({campaignId:campaign.id,campaignName:campaign.name,character:latest.character,records:latest.campaign,journal:latest.journal}));setMessage('AI package downloaded. Attach it with the transcript when asking AI for a campaign update.')}catch(error){setMessage(error instanceof Error?error.message:'Could not export the AI package.')}finally{setBusy(false)}};
  const choose=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);setMessage('Checking the update against the latest shared records…');try{const parsed=parseCampaignUpdate(await file.text());const latest=await loadLatest();const nextReviews=reviewCampaignUpdate(parsed,campaign.id,latest.campaign);setUpdate(parsed);setReviews(nextReviews);setSelected(new Set(nextReviews.filter(review=>review.status==='ready').map(review=>review.change.id)));setMessage(`${nextReviews.filter(review=>review.status==='ready').length} safe changes and ${nextReviews.filter(review=>review.status==='conflict').length} conflicts found.`)}catch(error){setUpdate(null);setReviews([]);setSelected(new Set());setMessage(error instanceof Error?error.message:'Could not read the campaign update.')}finally{setBusy(false)}};
  const apply=async()=>{if(!update)return;setBusy(true);setMessage('Rechecking shared records before applying…');try{const result=await applyChanges(update,selected);setMessage(`${result.applied} changes applied. ${result.conflicts?`${result.conflicts} changes were skipped because newer information exists.`:'No records were overwritten.'}`);setUpdate(null);setReviews([]);setSelected(new Set())}catch(error){setMessage(error instanceof Error?error.message:'Could not apply the campaign update.')}finally{setBusy(false)}};
  return <section className="card owner-ai-tools"><div className="section-head"><div><span className="eyebrow">CAMPAIGN OWNER ONLY</span><h2>AI session updates</h2></div></div><p className="lede">Export the newest shared campaign data, give it to AI with a transcript, then review the returned update here. Other players cannot see or use these controls.</p><div className="modal-actions"><button className="secondary" disabled={busy} onClick={exportPackage}><Download/>Prepare AI package</button><label className="primary file-btn"><Upload/>Review campaign update<input type="file" accept="application/json,.json" disabled={busy} onChange={choose}/></label></div>{message&&<p className="import-message">{message}</p>}{update?.warnings?.length?<div className="import-warnings"><b>AI warnings</b>{update.warnings.map((warning,index)=><p key={index}>{warning}</p>)}</div>:null}{reviews.length>0&&<div className="change-review"><h3>Proposed changes</h3>{reviews.map(review=><label className={`change-row ${review.status}`} key={review.change.id}><input type="checkbox" disabled={review.status==='conflict'} checked={selected.has(review.change.id)} onChange={event=>{const next=new Set(selected);if(event.target.checked)next.add(review.change.id);else next.delete(review.change.id);setSelected(next)}}/><span><b>{review.change.action}: {review.change.data.title}</b><small>{review.change.entityType} · {review.message}</small>{review.change.evidence&&<small>Evidence: {review.change.evidence}</small>}</span></label>)}<button className="primary" disabled={busy||selected.size===0} onClick={apply}>Apply {selected.size} approved changes</button></div>}</section>;
}
