import {useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {Anchor,Cloud,LogOut,Mail,Plus,RefreshCw,Users,X} from 'lucide-react';
import type {CloudCampaign,CloudStatus} from './cloud';
import {supabase} from './supabase';

export function AuthScreen(){
  const [email,setEmail]=useState(''),[sent,setSent]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');const redirect=new URL(import.meta.env.BASE_URL,window.location.origin).href;const {error:authError}=await supabase.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:redirect}});setBusy(false);if(authError)setError(authError.message);else setSent(true)};
  return <main className="auth-screen"><section className="auth-card"><div className="brandmark"><Anchor/></div><span className="eyebrow">PIRATE BORG COMPANION</span><h1>Sign in to your crew</h1>{sent?<><Mail className="auth-mail"/><h2>Check your email</h2><p>We sent a one-time sign-in link to <b>{email}</b>. Open it on this device to continue.</p><button onClick={()=>setSent(false)}>Use another email</button></>:<><p>Your email identifies which pirate and private journal entries belong to you. No password is required.</p><form onSubmit={submit}><label className="field"><span>Email address</span><input type="email" required autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="pirate@example.com"/></label>{error&&<p className="sync-error">{error}</p>}<button className="primary" disabled={busy}><Mail/>{busy?'Sending…':'Email me a sign-in link'}</button></form></>}</section></main>;
}

export function CloudBadge({campaign,status,onClick}:{campaign:CloudCampaign|null;status:CloudStatus;onClick:()=>void}){return <button className={`cloud-badge ${status}`} onClick={onClick}><Cloud/><span>{campaign?.name??'Join a campaign'}<small>{status==='syncing'?'Syncing…':status==='error'?'Offline changes waiting':status==='offline'?'Offline':'Cloud saved'}</small></span></button>}

export function CloudPanel({user,campaigns,activeId,status,onClose,onCreate,onJoin,onSwitch,onRetry}:{user:User;campaigns:CloudCampaign[];activeId:string|null;status:CloudStatus;onClose:()=>void;onCreate:(name:string)=>Promise<void>;onJoin:(code:string)=>Promise<void>;onSwitch:(id:string)=>Promise<void>;onRetry:()=>Promise<void>}){
  const [name,setName]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const run=async(work:()=>Promise<void>)=>{setBusy(true);setError('');try{await work()}catch(value){setError(value instanceof Error?value.message:'Cloud action failed')}finally{setBusy(false)}};
  const active=campaigns.find(campaign=>campaign.id===activeId);
  return <div className="modal-back"><div className="modal cloud-panel"><div className="modal-head"><div><span className="eyebrow">CONNECTED PLAYER</span><h2>Shared campaign</h2></div><button className="icon-btn" aria-label="Close cloud settings" onClick={onClose}><X/></button></div><div className="account-line"><Users/><div><b>{user.email}</b><span>{status==='synced'?'Everything is synchronized':status==='error'?'Some changes are waiting to sync':status}</span></div><button onClick={()=>supabase.auth.signOut()}><LogOut/>Sign out</button></div>{active&&<section className="campaign-code"><span className="eyebrow">CURRENT CAMPAIGN</span><h3>{active.name}</h3><p>Invite code: <b>{active.inviteCode}</b></p><small>Share this code only with members of your gaming group.</small></section>}<h3>Your campaigns</h3><div className="campaign-list">{campaigns.map(campaign=><button className={campaign.id===activeId?'active':''} key={campaign.id} onClick={()=>run(()=>onSwitch(campaign.id))}><Anchor/><span>{campaign.name}<small>{campaign.role}</small></span></button>)}{!campaigns.length&&<p>You have not joined a shared campaign yet.</p>}</div><div className="two-col cloud-forms"><form onSubmit={event=>{event.preventDefault();run(()=>onCreate(name)).then(()=>setName(''))}}><h3>Create a campaign</h3><input required value={name} onChange={event=>setName(event.target.value)} placeholder="Campaign name"/><button className="primary" disabled={busy}><Plus/>Create</button></form><form onSubmit={event=>{event.preventDefault();run(()=>onJoin(code)).then(()=>setCode(''))}}><h3>Join with a code</h3><input required value={code} onChange={event=>setCode(event.target.value.toUpperCase())} placeholder="Invite code"/><button className="primary" disabled={busy}><Users/>Join</button></form></div>{error&&<p className="sync-error">{error}</p>}{status==='error'&&<button className="secondary retry-sync" onClick={()=>run(onRetry)}><RefreshCw/>Retry waiting changes</button>}</div></div>;
}
